export const userData = [
    {
        email: "user1@example.com",
        username: "user1",
        password: "password1",
        address: "123 First St, City A, Country X",
        role: "user",
    },
    {
        email: "user2@example.com",
        username: "user2",
        password: "password2",
        address: "456 Second St, City B, Country Y",
        role: "user",
    },
    {
        email: "user3@example.com",
        username: "user3",
        password: "password3",
        address: "789 Third St, City C, Country Z",
        role: "user",
    },
    {
        email: "user4@example.com",
        username: "user4",
        password: "password4",
        address: "101 Fourth St, City D, Country W",
        role: "user",
    },
    {
        email: "user5@example.com",
        username: "user5",
        password: "password5",
        address: "202 Fifth St, City E, Country V",
        role: "user",
    },
    {
        email: "user6@example.com",
        username: "user6",
        password: "password6",
        address: "303 Sixth St, City F, Country U",
        role: "user",
    },
    {
        email: "user7@example.com",
        username: "user7",
        password: "password7",
        address: "404 Seventh St, City G, Country T",
        role: "user",
    },
    {
        email: "user8@example.com",
        username: "user8",
        password: "password8",
        address: "505 Eighth St, City H, Country S",
        role: "user",
    },
    {
        email: "admin1@example.com",
        username: "admin1",
        password: "adminpassword1",
        address: "606 Admin St, City I, Country R",
        role: "admin",
    },
    {
        email: "admin2@example.com",
        username: "admin2",
        password: "adminpassword2",
        address: "707 Admin St, City J, Country Q",
        role: "admin",
    },
];
